# Generated by Django 4.1.1 on 2022-11-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
